name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false  # if ture it fails every job if one jib failed
      max-parallel: 2  #max prallel jobs
      matrix:
        os: [ubuntu-latest, windows-latest,ubuntu-20.4]
        images: [hello-world ,alpine]
        exclude:
          - images: alpine
            os : windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.4

    runs-on: ${{matrix.os}}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{matrix.images}}

        run: docker run ${{matrix.images}}

# jobs:
#   deploy-on-ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info

#       - name: Run Images
#         run: docker run hello-world


#   deploy-on-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info

#       - name: Run Images
#         run: docker run hello-world
